### ISSUE TITLE
Implement `compress` command to write a BigArchive to disk from a directory structure

### ISSUE THREAD

**Issue by phrohdoh** [Phrohdoh/libbig#6]

**Comment by Teteros** [comment]
These might be useful as reference to implement this:

https://github.com/feliwir/libbig/issues/3#issuecomment-320371541
https://github.com/TheAssemblyArmada/Thyme/wiki/BIG-File-Format

**Comment by phrohdoh** [comment]
Thanks for the links @Teteros.
Unfortunately I don't have any BIG archives sitting around anymore (it has been awhile since I touched this project).

If you know of any small/test BIGs that would be super helpful.

**Comment by Teteros** [comment]
The other libbig has a sample https://github.com/feliwir/libbig/blob/master/tools/files/test.big

This one was made in FinalBIG (could be used in production/mod 'as is')
[Contra9B2BossEnabledNOH.zip](https://github.com/Phrohdoh/libbig/files/1379292/Contra9B2BossEnabledNOH.zip)

**Comment by phrohdoh** [comment]
@Teteros If you don't mind would you join me in the #orcaware channel on the Freenode IRC network so I may get a full picture of what you would like to get from this library.

I would rather spend time on items I know someone wants than guess and waste time.

**Comment by phrohdoh** [comment]
[easage](https://github.com/Phrohdoh/easage#examples) has implemented this in the form of a `pack` subcommand.
